### ISSUE TITLE
Nautilus extension doesn't work with Ubuntu 11.10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gborp/pagavcs#142]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 23, in <module>
    from ._gi import _API, Repository
ImportError: could not import gobject (error was: ImportError('When using 
gi.repository you must not import static modules like "gobject". Please change 
all occurrences of "import gobject" to "from gi.repository import GObject".',))

(nautilus:3948): Nautilus-Python-WARNING **: nautilus_python_init_python failed
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/pagavcs-nautilus.py", line 31, in <module>
    from gi.repository import Nautilus
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 23, in <module>
    from ._gi import _API, Repository
ImportError: cannot import name _API

```

Original issue reported on code.google.com by `gabor.pa...@gmail.com` on 22 Sep 2011 at 6:06
